#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.md from the modules actually linked into the
# binaries (go list -deps over ./cmd/...), not from go.mod, so build-only and
# tooling dependencies are excluded.
#
#   ./scripts/gen-notices.sh > THIRD-PARTY-NOTICES.md
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Best-effort license identification from the first lines of the license file.
classify() {
  local file="$1"
  # Dual-licensed files name both up front; check that before the single-license
  # patterns, which would otherwise report only whichever appears first.
  if grep -qi 'covered by two different licenses' "$file" 2>/dev/null; then
      echo "MIT AND Apache-2.0"
  elif grep -qi 'Apache License' "$file" 2>/dev/null; then echo "Apache-2.0"
  elif grep -qi 'MIT License' "$file" 2>/dev/null; then echo "MIT"
  elif grep -qi 'Permission is hereby granted, free of charge' "$file" 2>/dev/null; then echo "MIT"
  elif grep -qi 'Redistribution and use in source and binary forms' "$file" 2>/dev/null; then
      if grep -qi 'Neither the name' "$file" 2>/dev/null; then echo "BSD-3-Clause"; else echo "BSD-2-Clause"; fi
  elif grep -qi 'Mozilla Public License' "$file" 2>/dev/null; then echo "MPL-2.0"
  elif grep -qi 'ISC License' "$file" 2>/dev/null; then echo "ISC"
  else echo "see file"
  fi
}

cat <<'HEADER'
# Third-party notices

Scrubber is distributed under the MIT License (see `LICENSE`). It links the
open-source modules listed below, each under its own license. This file is
generated by `scripts/gen-notices.sh`; regenerate it whenever dependencies
change.

| Module | Version | License |
| --- | --- | --- |
HEADER

go list -deps -f '{{if .Module}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}{{end}}' ./cmd/... \
  | sort -u | grep -v '^$' | grep -v '^github.com/howard/scrubber' \
  | while IFS='|' read -r path version dir; do
      [ -z "$dir" ] && continue
      lic="$(find "$dir" -maxdepth 1 -iregex '.*/\(LICENSE\|LICENCE\|COPYING\)[^/]*' 2>/dev/null | head -1)"
      if [ -n "$lic" ]; then kind="$(classify "$lic")"; else kind="see module"; fi
      printf '| `%s` | %s | %s |\n' "$path" "$version" "$kind"
    done

cat <<'FOOTER'

Full license texts ship inside each module in the Go module cache and in any
vendored tree. To print one:

    go list -m -f '{{.Dir}}' <module> | xargs -I{} cat {}/LICENSE
FOOTER
